version: '3.4'


services:
  mysql:
    image: mysql:5.7.28
    ports: 
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    environment: 
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes: 
      - mysql_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - backend-network
    restart: always

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    depends_on:
      - "mysql"
    environment: 
      - PMA_ARBITRARY=1
    networks:
      - backend-network
      - frontend-network
    restart: always

  apache:
    build: ./apache
    ports: 
      - 80:80
    depends_on:
      - "mysql"
    networks:
      - backend-network
      - frontend-network
    restart: always

volumes:
  mysql_data:

networks:
  backend-network:
  frontend-network:
